//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Успеватория.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicPerfomance : Entity
    {
        public int ID { get; set; }
        public int IDLessons { get; set; }
        public int IDCousrseStudent { get; set; }
        public string Grade { get; set; }
    
        public virtual CourseStudent CourseStudent { get; set; }
        public virtual Lesson Lesson { get; set; }
    }
}
