//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Успеватория.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStudent : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseStudent()
        {
            this.AcademicPerfomances = new HashSet<AcademicPerfomance>();
        }
    
        public int ID { get; set; }
        public int IDCourse { get; set; }
        public int IDStudent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicPerfomance> AcademicPerfomances { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
