//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Успеватория.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentsChild : Entity
    {
        public int ID { get; set; }
        public int IDParent { get; set; }
        public int IDChildren { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
